routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Auth::routes();

Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::group(['prefix' => 'customers', 'as' => 'customers.'], function () {
        Route::get('/', 'App\Http\Controllers\CustomerController@index')->name('index');
        Route::get('edit/{customer}/customer', 'App\Http\Controllers\CustomerController@edit')->name('edit');
        Route::get('create', 'App\Http\Controllers\CustomerController@create')->name('create');
        Route::post('store', 'App\Http\Controllers\CustomerController@store')->name('store');
        Route::post('u/{customer}/update', 'App\Http\Controllers\CustomerController@update')->name('update');
        Route::get('d/{customer}/delete', 'App\Http\Controllers\CustomerController@destroy')->name('delete');
    });
	
	Route::group(['prefix' => 'transactions', 'as' => 'transactions.'], function () {
        Route::get('/', 'App\Http\Controllers\TransactionController@index')->name('index');
        Route::get('edit/{transaction}/transaction', 'App\Http\Controllers\TransactionController@edit')->name('edit');
        Route::get('select', 'App\Http\Controllers\TransactionController@select')->name('select');
        Route::get('create', 'App\Http\Controllers\TransactionController@create')->name('create');
        Route::post('store', 'App\Http\Controllers\TransactionController@store')->name('store');
        Route::post('u/{transaction}/update', 'App\Http\Controllers\TransactionController@update')->name('update');
        Route::get('d/{transaction}/delete', 'App\Http\Controllers\TransactionController@destroy')->name('delete');
    });

	Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
});

Route::group(['middleware' => 'auth'], function () {
	Route::get('{page}', ['as' => 'page.index', 'uses' => 'App\Http\Controllers\PageController@index']);
});

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Customer;
use App\Models\Transaction;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class TransactionController extends Controller
{
    /**
     * Display a listing of the transactions
     *
     * @param  \App\Models\Transaction  $model
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $transactions = Transaction::select([
            '*', 
            DB::raw('(SELECT name FROM customers WHERE customers.id = transactions.sender) as senderid'),
            DB::raw('(SELECT name FROM customers WHERE customers.id = transactions.receiver) as receiverid')
            ])->get();
        return view('transactions.index', compact('transactions'));
    }

    /**
     * Show the form for selecting a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function select()
    {
        $customers = Customer::latest()->paginate(100);
        return view('transactions.select', compact('customers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $customers = Customer::latest()->paginate(100);
        return view('transactions.create', compact('customers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $rq
     * @return \Illuminate\Http\Response
     */
    public function store(Request $rq)
    {
        Transaction::create($rq->all());
        return redirect()->route('transactions.index')->with('success', 'Transaction created successfully.');
    }

    /**
     * Show the form for editing the profile.
     *
     * @return \Illuminate\View\View
     */
    public function edit(Transaction $transaction)
    {
        return view('transactions.edit', compact('transaction'));
    }

    /**
     * Show the form for viewing the profile.
     *
     * @return \Illuminate\View\View
     */
    public function view(Transaction $transaction)
    {
        return view('transactions.view', compact('transaction'));
    }

    /**
     * Update the resource
     *
     * @param  \App\Http\Requests\Request  $rq
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $rq, Transaction $transaction)
    {
        try {
            $transaction->update($rq->all());
            return redirect()->route('transactions.index')->with('success', 'Transaction updated successfully.');
        } catch (\Exception $exception) {
            return redirect()->back()->withError('Error while updating Transaction');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Apptime  $apptime
     * @return \Illuminate\Http\Response
     */
    public function destroy(Transaction $transaction)
    {
        $transaction->delete();
        return redirect()->route('transactions.index')->with('success', 'Transaction deleted successfully');
    }
    
}

resources/views/transactions/create.blade.php
@extends('layouts.app', [
    'class' => '',
    'elementActive' => 'transactions'
])

@section('content')
    <div class="content">
        @if (session('status'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ session('status') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
        <div class="row">                
            <div class="col-md-8 text-center">
                <form class="col-md-12" action="{{ route('transactions.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <input type="hidden" name="sender" value="{{ request('sender') }}" required>
                    <input type="hidden" name="code" value="OGA<?php $time_stamp = "'" . time() . "'";
                    echo $time_stamp[1].$time_stamp[4].$time_stamp[7].$time_stamp[10]; ?>X" required>
                    <div class="card">
                        <div class="card-header">
                            <h5 class="title">{{ __('New Transaction') }}</h5>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <label class="col-md-3 col-form-label">{{ __('Select Receiver') }}</label>
                                <div class="col-md-9">
                                    <div class="form-group">
                                        @foreach ($customers as $customer)
                                            @if ($customer->id != request('sender'))
                                                <div class="row">
                                                    <label>
                                                        <input type="radio" name="receiver" value="{{ $customer->id }}" required>
                                                        {{ $customer->name }}
                                                    </label>
                                                </div>
                                            @endif
                                        @endforeach
                                    </div>
                                    @if ($errors->has('receiver'))
                                        <span class="invalid-feedback" style="display: block;" role="alert">
                                            <strong>{{ $errors->first('receiver') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-md-3 col-form-label">{{ __('Amount (Kshs)') }}</label>
                                <div class="col-md-9">
                                    <div class="form-group">
                                        <input type="number" name="amount" class="form-control" min="100" required>
                                    </div>
                                    @if ($errors->has('amount'))
                                        <span class="invalid-feedback" style="display: block;" role="alert">
                                            <strong>{{ $errors->first('amount') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="card-footer ">
                            <div class="row">
                                <div class="col-md-12 text-center">
                                    <button type="submit" class="btn btn-info btn-round">{{ __('Finish Transaction') }}</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                
            </div>
        </div>
    </div>
@endsection

resources/views/transactions/index.blade.php
@extends('layouts.app', [
    'class' => '',
    'elementActive' => 'transactions'
])

@section('content')
    <div class="content">        
        @if (session('status'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ session('status') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
        <div class="container-fluid mt--7">
            <div class="row">
                <div class="col">
                    <div class="card shadow">
                        <div class="card-header border-0">
                            <div class="row align-items-center">
                                <div class="col-8">
                                    <h3 class="mb-0">Transactions</h3>
                                </div>
                                <div class="col-4 text-right">
                                    <a href="{{ route('transactions.select') }}" class="btn btn-sm btn-primary">Add a Transaction</a>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-12">
                            <table class="table align-items-center table-flush">
                                <thead class="thead-light">
                                    <tr>
                                        <th scope="col">Date/Time</th>
                                        <th scope="col">Sender Name</th>
                                        <th scope="col">Beneficiary</th>
                                        <th scope="col">Amount</th>
                                        <th scope="col">Ref. Code</th>
                                        <th scope="col">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($transactions as $transaction)
                                    <tr>
                                        <td>{{ $transaction->created_at }}</td>
                                        <td>{{ $transaction->senderid }}</td>
                                        <td>{{ $transaction->receiverid }}</td>
                                        <td>{{ $transaction->amount }}</td>
                                        <td>{{ $transaction->code }}</td>
                                        <td class="text-right">
                                            <div class="dropdown">
                                                <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <i class="fas fa-ellipsis-v"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                    <a class="dropdown-item" href="{{ route('transactions.delete', $transaction->id) }}" onclick="return confirm('Are you sure you want to delete this transaction from the system? \nBe careful, this action can not be reversed.')">Delete Transaction</a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
        
                        
                        <div class="card-footer py-4">
                            <nav class="d-flex justify-content-end" aria-label="...">
                                
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/transactions/select.blade.php
@extends('layouts.app', [
    'class' => '',
    'elementActive' => 'transactions'
])

@section('content')
    <div class="content">
        @if (session('status'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ session('status') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
        <div class="row">                
            <div class="col-md-8 text-center">
                <form class="col-md-12" action="{{ route('transactions.create') }}" method="GET">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="title">{{ __('New Transaction') }}</h5>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <label class="col-md-3 col-form-label">{{ __('Select Sender') }}</label>
                                <div class="col-md-9">
                                    <div class="form-group">
                                        @foreach ($customers as $customer)
                                            <div class="row">
                                                <label>
                                                    <input type="radio" name="sender" value="{{ $customer->id }}" required>
                                                    {{ $customer->name }}
                                                </label>
                                            </div>
                                        @endforeach
                                    </div>
                                    @if ($errors->has('sender'))
                                        <span class="invalid-feedback" style="display: block;" role="alert">
                                            <strong>{{ $errors->first('sender') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="card-footer ">
                            <div class="row">
                                <div class="col-md-12 text-center">
                                    <button type="submit" class="btn btn-info btn-round">{{ __('Proceed with the Transaction') }}</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                
            </div>
        </div>
    </div>
@endsection